# backend/docker-compose.yml

services:
  strapi:
    container_name: strapi
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: development
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/app/package.json
      - ./yarn.lock:/opt/app/yarn.lock
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - strapi
    depends_on:
      - strapiDB
      - redis # Added Redis as a dependency

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: tnt_mkr_db_user
      POSTGRES_PASSWORD: Applesauce@777
      POSTGRES_DB: tnt-mkr-database
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - strapi

  redis:
    container_name: redis
    image: redis:6-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    driver: bridge
